config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :products do
    resources :comments
  end
  devise_for :users
  resources :users

  resources :object_names
  resources :orders, only: [:index, :show, :create, :destroy]
  post 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  # When your application receives a request without a path it will invoke the landing_page action in the simple_pages controller.
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/object_name.rb
class ObjectName < ApplicationRecord
end

app/controllers/object_names_controller.rb
class ObjectNamesController < ApplicationController
  before_action :set_object_name, only: [:show, :edit, :update, :destroy]

  # GET /object_names
  # GET /object_names.json
  def index
    @object_names = ObjectName.all
  end

  # GET /object_names/1
  # GET /object_names/1.json
  def show
  end

  # GET /object_names/new
  def new
    @object_name = ObjectName.new
  end

  # GET /object_names/1/edit
  def edit
  end

  # POST /object_names
  # POST /object_names.json
  def create
    @object_name = ObjectName.new(object_name_params)

    respond_to do |format|
      if @object_name.save
        format.html { redirect_to @object_name, notice: 'Object name was successfully created.' }
        format.json { render :show, status: :created, location: @object_name }
      else
        format.html { render :new }
        format.json { render json: @object_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /object_names/1
  # PATCH/PUT /object_names/1.json
  def update
    respond_to do |format|
      if @object_name.update(object_name_params)
        format.html { redirect_to @object_name, notice: 'Object name was successfully updated.' }
        format.json { render :show, status: :ok, location: @object_name }
      else
        format.html { render :edit }
        format.json { render json: @object_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_names/1
  # DELETE /object_names/1.json
  def destroy
    @object_name.destroy
    respond_to do |format|
      format.html { redirect_to object_names_url, notice: 'Object name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_object_name
      @object_name = ObjectName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def object_name_params
      params.fetch(:object_name, {})
    end
end

app/helpers/object_names_helper.rb
module ObjectNamesHelper
end

app/views/object_names/_form.html.erb
<%= form_with(model: object_name, local: true) do |form| %>
  <% if object_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object_name.errors.count, "error") %> prohibited this object_name from being saved:</h2>

      <ul>
      <% object_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/object_names/edit.html.erb
<h1>Editing Object Name</h1>

<%= render 'form', object_name: @object_name %>

<%= link_to 'Show', @object_name %> |
<%= link_to 'Back', object_names_path %>

app/views/object_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Object Names</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @object_names.each do |object_name| %>
      <tr>
        <td><%= link_to 'Show', object_name %></td>
        <td><%= link_to 'Edit', edit_object_name_path(object_name) %></td>
        <td><%= link_to 'Destroy', object_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% paragraph_number = 1 %>
<% 5.times do %>
  <p>This is paragraph number <%= paragraph_number %></p>
  <% paragraph_number = paragraph_number + 1 %>
<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Object Name', new_object_name_path %>

app/views/object_names/new.html.erb
<h1>New Object Name</h1>

<%= render 'form', object_name: @object_name %>

<%= link_to 'Back', object_names_path %>

app/views/object_names/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_object_name_path(@object_name) %> |
<%= link_to 'Back', object_names_path %>
<%= @product.comments.order(rating: :desc).first %>