config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :products do
    resources :comments
  end
  devise_for :users
  resources :users

  resources :object_names
  resources :orders, only: [:index, :show, :create, :destroy]
  post 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  # When your application receives a request without a path it will invoke the landing_page action in the simple_pages controller.
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Nameofapp</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
          <% end %>
        </li>
      </ul>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <footer>
      &copy; 2018 Bike Berlin
    </footer>
  </body>
</html>